<%	
dim Recordatorio,FechaRecordatorio, ObsRecordatorio, Tarea, FechaTarea, EjecutorTarea, DescTarea, Cita, FechaCita, FechaVencimiento, FechaAviso, FechaCumple, FechaCompromiso
dim langtext(13)
Recordatorio = 1
FechaRecordatorio = 2
ObsRecordatorio = 3
Tarea = 4
FechaTarea = 5
EjecutorTarea = 6
DescTarea = 7
Cita = 8
FechaCita = 9
FechaVencimiento = 10
FechaAviso = 11
FechaCumple = 12
FechaCompromiso = 13

langtext(Recordatorio)="Reminder"
langtext(FechaRecordatorio)="ReminderDate"
langtext(ObsRecordatorio)="ReminderComment"
langtext(Tarea)="Task"
langtext(FechaTarea)="TaskDate"
langtext(EjecutorTarea)="TaskExecutor"
langtext(DescTarea)="TaskDesc"
langtext(Cita)="Appointment"
langtext(FechaCita)="AppDate"
langtext(FechaVencimiento)="DueDate"
langtext(FechaAviso)="AgreedDate"
langtext(FechaCumple)="DeadLine"
langtext(FechaCompromiso)="CommitmentDate"

%>