var langtext=[
    { 
        "Textos en Scripts":"langtext[0].;",
        "TextoCantidad":"Amount",
        "Ejemplo1":"Example 1",
        "Ejemplo2":"Example 2",
        "Ejemplo3":"Example 3",
        "AlertaSincDossier":"This Dossier is sincronizing now, try later",
        "initImageImportText":"<p>Please select a file</p>",
        "errorReadingFileText":"Error reading file",
        "noPdfFileText":" not a pdf file.",
        "signPleaseText":"Sign please",
        "mustTakePictureText":"Must take Picture from Camera",
        "mustEnterValueText":"Must enter value for ",
        "mustEnterCorrectlyText":"Must enter correctly ",
        "mustSelectValueText":"Must select a value for ",
        "imageMustBeFromCameraText":"Image must be from Camera",
        "userDeniedGeolocationText":"User denied geolocation request",
        "noLocationInfoText":"No location information available",
        "geolocationTimedOutText":"Geolocation timed out",
        "errorDesconocidoText":"Unknown error",
        "tryAgainSoonText":"Tray again in a while...",
        "mustBeApprovedBySupervisorText":"Must be approved by supervisor",
        "cantRegisterText":"Cannot register ",
        "commaResultIsText":", result: ",
        "approvedByText":"Approved_by",
        "cantTakeSupervisorText":"Cannot scan supervisor fingerprint:",
        "getFingerPrintText":"Getting fingerprint",
        "enterIdToRegFingerPrintText":"Must enter Id number to save fingerprint",
        "mustEnterIdText":"Must enter ID number",
        "mustEnterLastNameText":"Must enter LastName to save fingerprint",
        "mustEnterNameText":"Must enter Name to save fingerprint",
        "mustEnterAllText":"Must enter Id number, Name and LastName to save fingerprint",
        "couldNotExecText":"Could not execute operation ",
        "cantGetFingerPrintText":"Could not scan fingerprint :",
        "cantDelFingerPrintText":"Could not delete fingerprint :",
        "errorSavingDC":"Error saving DataClip:",
        "Cita":"Appointment",
        "Tarea":"Task",
        "Anexo":"Attachment",
        "DescAnexo":"Description of Attachment",
        "PrevDC":"Prev DC",
        "EditDC":"Edit DC",
        "EditStatus":"Change Status",
        "DCSaved":"DC Saved",
        "Imprimir":"Print",
        "Recordatorio":"Reminder",
        "Vencimiento":"Due_Date",
        "Approval":"Approval",
        "problemSavingText":"Problems saving info, tray again ",
        "Lunes":"Monday",
        "Lun":"Mon",
        "Martes":"Tuesday",
        "Mar":"Tue",
        "Miercoles":"Wendsday",
        "Mie":"Wen",
        "Jueves":"Thursday",
        "Jue":"Thu",
        "Viernes":"Friday",
        "Vie":"Fri",
        "Sabado":"Saturday",
        "Sab":"Sat",
        "Domingo":"Sunday",
        "Dom":"Sun",
        "Enero":"January",
        "Febrero":"February",
        "Marzo":"March",
        "Abril":"April",
        "Mayo":"May",
        "Junio":"June",
        "Julio":"July",
        "Agosto":"Agost",
        "Septiembre":"September",
        "Octubre":"October",
        "Noviembre":"November",
        "Diciembre":"December",
        "apply":"Acept",
        "cancel":"Cancel",
        "keyboardShortcuts":"Key suggestions",
        "selectedDateText":"Select highlighted date",
        "EnterKeyText":"Enter Key",
        "leftRight4Days":"Go back (left) and next (right) one day.",
        "LeftRightKeysText":"Left or Right Keys",
        "upDown4Weeks":"Go back (up) and next (down) a week.",
        "UpDownKeysText":"Up and Down Keys",
        "symbolRePagAvPatText":"PageDwn/PageUp",
        "cambioMes":"Change month.",
        "RePagAvPagKeysText":"PageDown and PageUp Keys",
        "symbolInicioFinText":"Home/End",
        "firstLastWeekText":"Go to first day or last day of week.",
        "InicioFinKeysText":"Home or End Keys",
        "symbolEscText":"Esc",
        "closePanelText":"Close this panel",
        "EscKeyText":"Escape Key",
        "openPanelText":"Open this panel",
        "QuestionKeyText":"Question",
        "errorStructTransferText":"error getting current group file (profile security)",
        "errorStructTransferLocalText":"error getting current group file locally",
        "errorStructTransferLocalSecText":"error getting current group file locally (profile security)",
        "errorStructTransferRemoteText":"error getting current group file over the web",
        "tryAgain":"Try again",
        "cantLoadDataClip":"1-Cannot get DataClip ",
        "cantLoadDataClip2":"2-Cannot get DataClip ",
        "cantEditClipText":"cannot edit this DataClip!",
        "authProblems":"Authorization restriction: ",
        "errorRetreivingDossierText":"error getting dossiers",
        "errorLoadingDC2DeskText":"error getting DataClip to Edit and Desktop",
        "errorReadingGrupoText":"error getting current group file",
        "errorSelGrupoChartText":"error selecting group file in Charts",
        "Usuario":"User",
        "Usuario_DC":"User_DC",
        "Hora":"Hour",
        "Hora_DC":"Hour_DC",
        "Fecha":"Date",
        "Fecha_DC":"Date_DC",
        "Titulo":"Title",
        "errorGettingGrupoText":"error getting user groups",
        "errorGettingGrupoChartText":"error getting user groups in charts",
        "errorGetGrupoRexText":"error getting group file selecting dossier",
        "errorGetGrupoText":"error getting group file",
        "errorGetGrupoDefaultText":"error getting default group file",
        "errorGetGrupo4DCs":"error getting DataClip file",
        "errorDrawSelChartText":"error drawing current chart",
        "Cantidad":"Amount",
        "Todos":"All",
        "Activos":"Active",
        "Historicos":"Archived",
        "ActivosHistoricos":"Active & Archived",
        "Descripcion":"Description",
        "ObsRecordatorio":"ReminderComment",
        "FechaRecordatorio":"ReminderDate",
        "HoraRecordatorio":"ReminderHour",
        "Observacion":"Comment",
        "Repetir":"Repeat",
        "NoRepite":"Once",
        "Semanalmente":"Weekly",
        "Mensualmente":"Monthly",
        "Anualmente":"Yearly",
        "ObsCita":"AppComment",
        "FechaCita":"AppDate",
        "HoraCita":"AppHour",
        "Nombre":"Name",
        "Telefono":"Phone",
        "DescTarea":"TaskDesc",
        "Ejecutor":"Executor",
        "EjecutorTarea":"TaskExecutor",
        "FechaTarea":"TaskDate",
        "HoraTarea":"TaskHour",
        "AllUsersText":"All users",
        "Historico":"Archived",
        "SessionMenuText":"Session menu ",
        "Aceptada":"Acepted",
        "EnProgreso":"In progress",
        "Lista":"Ready",
        "Incompleta":"Incomplete",
        "Anulada":"Canceled",
        "Borrada":"Deleted",
        "Listo":"Ready",
        "errorSetEstadoRexText":"error setting dossier status:",
        "newPwd2Short":"New pwd must have 6 or more characters",
        "mustBeEqualPwds":"New and confirmed pwd must match!",
        "errorSetNewPwd":"error setting new pwd: ",
        "setNewPwdOk":"New Password set!",
        "wantReStartDossier":"Re-start Dossier?",
        "editDC":"Edit DataClip",
        "EditStatus":"Change Status",
        "Imprimir":"Print",
        "DCSaved":"DC edited",
        "PrevDC":"DC Antiguo",
        "EditDC":"Edit Dataclip",
        "errorGeoLocation":"FYI: Geolocation services failed.",
        "errorBrowserNoSupportGeoloc":"FYI: browser does not support geolocation.",
        "AgregarTarea":"Add Task",
        "OrdenarDCs":"Sort Dataclips",
        "RotIzq":"rotate left",
        "RotDer":"rotate right",
        "AgregarDC":"Add DataClip",
        "AgregarImg":"Add Image",
        "OtrasOps":"Other Commands",
        "errorRDSRadioCheck":"error setting Radio/Check data",
        "errorGetJsonSpin":"Error setting Spin option data",
        "Selecciona":"Select ...",
        "errorGetAssetsJson":"error getting assets",
        "NotFound":"Not found",
        "errorRds":"error getting data from web",
        "errorIdNotRespondigFP":"Id not responding, verify scan protocol",
        "errorNoProfileSet":"No profile asigned",
        "PorLic":"licence issue",
        "NotReg":"Not registered issue",
        "NoFPScanner":"cannot recognize biometric scanner",
        "errorCaptura":"error scanning fingerprint",
        "errorGeneralFP":"fingerprint scanning process error",
        "errorCapturaImagenTemplate":"error in scanning fingerprint image and template",
        "errorBDConnect":"Nserver database connection error",
        "noConnectNServer":"no communication with Nserver",
        "FPCanceled":"Scan process canceled",
        "errorNserver":"Update Nserver error",
        "incorrectParameters":"incorrect query parameters",
        "FPRegistrada":"FingerPrint already registered in database",
        "FPIdRegistrado":"Id Number already registered in database",
        "noRegistroDeFPEnNserver":"Nserver biometric register not completed",
        "unknownError":"unknown",
        "quieresLogout":"Logout of work session?"
    },
    {
        "Titles en html":"",
        "IngresaId":"Enter Id",
        "IngresaPwd":"Enter Password",
        "iconRotateLeft":"rotate left",
        "iconRotateRight":"rotate right",
        "iconAddDC":"Add DataClip",
        "iconAddTask":"Add Task",
        "iconAddImg":"Add Image",
        "iconOtherOps":"Other Commands",
        "iconPrevDC":"Prev DC",
        "Cita":"Appointment",
        "Recordatorio":"Reminder",
        "aicon":"session menu",
        "BuscarEnDossiers":"Search in Dossier database",
        "iconSelectGrupo":"Select group",
        "iconSelEquipo":"Select a user",
        "SelStatusTitle":"Select Dossier Status",
        "iconRangoFecha":"Set date range",
        "ButSubirEnMemoria":"Upload unsaved Dossiers",
        "butDondeBusqueda":"Search on Map",
        "iconRefresh":"refresh",
        "GraficarDossiers":"Chart Dossiers",
        "iconExportaExcel":"Export to Excel(csv)",
        "iconPrint":"Print",
        "iconChartSelectGroup":"Select group",
        "iconTipoDossier":"Select type of Dossier",
        "ChartIconSelDC":"Select a DataClip",
        "iconSelCampoDC":"Select a field in DC",
        "iconChartSelectSello":"Select a stamp",
        "iconChartEstadoDossier":"Select Dossier status",
        "iconChartMiembroEquipo":"Select a user",
        "iconChartRangoFecha":"Set date range",
        "iconChartPeq":"smaller",
        "iconChartRefresh":"refresh",
        "expandicon":"bigger",
        "iconChartRefresh2":"refresh",
        "expandicon2":"bigger",
        "iconChartPeq2":"smaller",
        "iconChartRefresh3":"refresh",
        "expandicon3":"bigger",
        "iconChartPeq3":"smaller",
        "IngresaClaveText":"Current password",
        "IngresaClaveNuevaText":"New password",
        "ConfirmaClaveNuevaText":"Confirma new password",
        "Editando":"Edit DC",
        "DCcamera":"Take Picture",
        "DCgallery":"Get Image",
        "PdfDC":"Get PDF",
        "DCFingerPrintButt":"FingerPrint Id",
        "DCsignature":"Get Signature",
        "DeleteImagefromDC":"Delete Image",
        "ImportSelected":"Get info from selected DC"       
    },
    {
        "alt Texts": "",
        "NextCameraIcon":"Next Camera",
        "TakeFotoIcon": "Take Picture"
    },
    {
        "innerHTML Text":"",
        "EnterButt":"Enter",
        "Version":"Version",
        "CameraTitle":"Camera",
        "Donde1":" Where",
        "Donde3":"Where",
        "Cuando1":" When",
        "Cuando3":"When",
        "Estadisticas1":" Analyze",
        "Estadisticas3":"Analyze",
        "Graficos3":"Chart",
        "CerrarSesion":"Logout",
        "CambioPwd":"Change password",
        "FirstSelGrupoOption":"All",
        "FirstSelEquipoOption":"All",
        "SelStatus1":"Active",
        "SelStatus2":"Archived",
        "SelStatus3":"Closed",
        "SelStatus0":"Deleted",
        "BuscarButton":"<span class='glyphicon glyphicon-search'></span> Search",
        "CantTareasPend":" Tasks",
        "CantRemindersPend":" Reminders",
        "CantDatesPend":" Appointments",
        "CantEnMemoria":" Unsaved",
        "CantidadDossiers":"Amount",
        "ChartFirstSelGrupoOption":"All",
        "ChartFirstSelDossierOption":"All",
        "FirstChartDCOption":"All",
        "SelCamposMostrar":"Select fields to show",
        "ChartFirstSelloOption":"Not stamped",
        "ChartStatusActivos":"Active",
        "ChartStatusHistoricos":"Archived",
        "ChartStatusActHist":"Active & Archived",
        "FirstChartOptionEquipo":"All",
        "TextoArchivoGaleria":"Image file",
        "TextSelFile":"Select an image",
        "NoSelText":"No selection",
        "PdfFileText":"PDF file",
        "SelPdfText":"Select a pdf file",
        "NoPdfSelected":"No selection",
        "CalendarText":"Calendar",
        "EstadisticasText":"Analyze",
        "iconArriba":"up",
        "EstadoTextOtrasOps":"Status:",
        "ActivoStatusText":"Active",
        "HistStatusText":"Archived",
        "BorradoStatusText":"Deleted",
        "SetRexStatusButt":"Change status",
        "ChangePwdText":"Change password:",
        "PwdActualText":"current",
        "PwdNuevoText":"new",
        "PwdConfirmText":"confirm",
        "ButCambiaPwd":"Change password",
        "Editor_DataClipName":"DataClip name",
        "SignatureText":"Sign here",
        "SellosText":"Stamps",
        "SellosComentarioText":"Comment:",
        "OrdenarDCText":"Sort DCs",
        "AddFileText":"Image attachment",
        "AddFileDescText":"Description:",
        "AddFileSelImageText":"Select an image",
        "AddFileNoSel":"No selection",
        "followUs":"Follow us"
    },
    {
        "Placeholders":"",
        "enTitulo":"Search in Dossier",
        "TextoChart":"Filter text",
        "iconChartSelectGroup":"Select group"
    }

];
function SetCurrentLanguageTexts(){
    var elem=null;
    
    for(var Tit in langtext[1]){//Titles
        try{
            elem = document.getElementById(Tit);
            elem.title = langtext[1][Tit];
        }catch(e){}
    }
    for(var alts in langtext[2]){//Titles
        try{
            elem = document.getElementById(alts);
            elem.alt = langtext[2][alts];
        }catch(e){}
    }
    for(var inners in langtext[3]){//Titles
        try{
            elem = document.getElementById(inners);
            elem.innerHTML = langtext[3][inners];
        }catch(e){}
    }
    for(var places in langtext[4]){//Titles
        try{
            elem = document.getElementById(places);
            elem.placeholder = langtext[4][places];
        }catch(e){}
    }

}




