var langtext=[
    { 
        "Textos en Scripts":"langtext[0].;",
        "TextoCantidad":"Cantidad",
        "Ejemplo1":"Ejemplo 1",
        "Ejemplo2":"Ejemplo 2",
        "Ejemplo3":"Ejemplo 3",
        "AlertaSincDossier":"Este Dossier se esta sincronizando, trata en un rato",
        "initImageImportText":"<p>Sin seleccionar</p>",
        "errorReadingFileText":"Error leyendo archivo",
        "noPdfFileText":" no es un archivo pdf.",
        "signPleaseText":"Firme por favor",
        "mustTakePictureText":"Debe tomar un Fotografia desde la Camara",
        "mustEnterValueText":"Debes ingresar un valor para ",
        "mustEnterCorrectlyText":"Debes ingresar correctamente el ",
        "mustSelectValueText":"Debes seleccionar un valor para ",
        "imageMustBeFromCameraText":"La imagen a tomar debe ser desde la Camara",
        "userDeniedGeolocationText":"Usuario nego el pedido para Geolocalizacion",
        "noLocationInfoText":"Informacion de localizacion no esta disponible",
        "geolocationTimedOutText":"Tiempo de localizacion excedido",
        "errorDesconocidoText":"Ocurrio error desconocido",
        "tryAgainSoonText":"Trate nuevamente en un rato...",
        "mustBeApprovedBySupervisorText":"Se solicita aprobacion de un supervisor",
        "cantRegisterText":"No se pudo registrar a ",
        "commaResultIsText":", resultado: ",
        "approvedByText":"Aprobado_por",
        "cantTakeSupervisorText":"No se pudo tomar huella del supervisor:",
        "getFingerPrintText":"Se procede a tomar la huella",
        "enterIdToRegFingerPrintText":"Debes ingresar un numero de cedula para registrar huella",
        "mustEnterIdText":"Debes ingresar una Cedula",
        "mustEnterLastNameText":"Debes ingresar un Apellido para registrar huella",
        "mustEnterNameText":"Debes ingresar un Nombre para registrar huella",
        "mustEnterAllText":"Debes ingresar Cedula, Nombres y Apellidos para registrar huella",
        "couldNotExecText":"No se pudo realizar la operacion a ",
        "cantGetFingerPrintText":"No se pudo tomar la huella :",
        "cantDelFingerPrintText":"No se pudo eliminar la huella :",
        "errorSavingDC":"Error en SaveDC:",
        "Tarea":"Tarea",
        "Anexo":"Anexo",
        "Recordatorio":"Recordatorio",
        "Vencimiento":"Vencimiento",
        "Approval":"Approval",
        "problemSavingText":"Problemas salvando, trate nuevamente ",
        "Lunes":"Lunes",
        "Lun":"Lun",
        "Martes":"Martes",
        "Mar":"Mar",
        "Miercoles":"Miercoles",
        "Mie":"Mie",
        "Jueves":"Jueves",
        "Jue":"Jue",
        "Viernes":"Viernes",
        "Vie":"Vie",
        "Sabado":"Sabado",
        "Sab":"Sab",
        "Domingo":"Domingo",
        "Dom":"Dom",
        "Enero":"Enero",
        "Febrero":"Febrero",
        "Marzo":"Marzo",
        "Abril":"Abril",
        "Mayo":"Mayo",
        "Junio":"Junio",
        "Julio":"Julio",
        "Agosto":"Agosto",
        "Septiembre":"Septiembre",
        "Octubre":"Octubre",
        "Noviembre":"Noviembre",
        "Diciembre":"Diciembre",
        "apply":"Aceptar",
        "cancel":"Cancelar",
        "keyboardShortcuts":"Sugerencia Teclas",
        "selectedDateText":"Seleciona la fecha resaltada",
        "EnterKeyText":"Tecla Intro",
        "leftRight4Days":"Ir atras (izq) y adelante (der) por un dia.",
        "LeftRightKeysText":"'Teclas direccionales de Izq o Der'",
        "upDown4Weeks":"Ir atras (arriba) y adelante (abajo) por una semana.",
        "UpDownKeysText":"Teclas direccionales de arriba y abajo",
        "symbolRePagAvPatText":"RePag/AvPag",
        "cambioMes":"Cambia de mes.",
        "RePagAvPagKeysText":"Teclas de RePag y AvPag",
        "symbolInicioFinText":"Inicio/Fin",
        "firstLastWeekText":"Ve al primer o ultimo dia de la semana.",
        "InicioFinKeysText":"Teclas de Inicio o Fin",
        "symbolEscText":"Esc",
        "closePanelText":"Cierra este panel",
        "EscKeyText":"Tecla de Escape",
        "openPanelText":"Abre este panel",
        "QuestionKeyText":"Interrogacion",
        "errorStructTransferText":"Error transfiriendo estructura del grupo actual por seguridad",
        "errorStructTransferLocalText":"Error transfiriendo estructura del grupo actual localmente",
        "errorStructTransferLocalSecText":"Error transfiriendo estructura del grupo actual localmente por seguridad",
        "errorStructTransferRemoteText":"Error transfiriendo estructura del grupo actual, remotamente",
        "tryAgain":"Trata nuevamente",
        "cantLoadDataClip":"1-No pudo cargar el dataclip ",
        "cantLoadDataClip2":"2-No pudo cargar el dataclip ",
        "cantEditClipText":"Este DataClip no se puede modificar actualmente!",
        "authProblems":"Problemas con la autorizacion: ",
        "errorRetreivingDossierText":"Error trayendo dossiers",
        "errorLoadingDC2DeskText":"Error cargando DataClip al Editor y al escritorio",
        "errorReadingGrupoText":"Error leyendo estructura del grupo seleccionado",
        "errorSelGrupoChartText":"Error al seleccionar la estructura del grupo Json en el tipo de grafico a mostrar",
        "Usuario":"Usuario",
        "Usuario_DC":"Usuario_DC",
        "Hora":"Hora",
        "Hora_DC":"Hora_DC",
        "Fecha":"Fecha",
        "Fecha_DC":"Fecha_DC",
        "Titulo":"Titulo",
        "errorGettingGrupoText":"Error leyendo los grupos al que pertenece el usuario",
        "errorGettingGrupoChartText":"Error leyendo los grupos al que pertenece el usuario en graficos",
        "errorGetGrupoRexText":"Error leyendo estructura del grupo al seleccionar un rex",
        "errorGetGrupoText":"Error al leer estructura de grupo",
        "errorGetGrupoDefaultText":"Error al leer estructura de grupo para seleccionarlo como por omision",
        "errorGetGrupo4DCs":"Error al leer estructura de grupo para los DataClips",
        "errorDrawSelChartText":"Error dibujando el grafico seleccionado",
        "Cantidad":"Cantidad",
        "Todos":"Todos",
        "Activos":"Activos",
        "Historicos":"Historicos",
        "ActivosHistoricos":"Activos & Historicos",
        "Descripcion":"Descripcion",
        "ObsRecordatorio":"ObsRecordatorio",
        "FechaRecordatorio":"FechaRecordatorio",
        "HoraRecordatorio":"HoraRecordatorio",
        "Observacion":"Observacion",
        "Repetir":"Repetir",
        "NoRepite":"No Repite",
        "Semanalmente":"Semanalmente",
        "Mensualmente":"Mensualmente",
        "Anualmente":"Anualmente",
        "ObsCita":"ObsCita",
        "FechaCita":"FechaCita",
        "HoraCita":"HoraCita",
        "Nombre":"Nombre",
        "Telefono":"Telefono",
        "DescTarea":"DescTarea",
        "Ejecutor":"Ejecutor",
        "EjecutorTarea":"EjecutorTarea",
        "FechaTarea":"FechaTarea",
        "HoraTarea":"HoraTarea",
        "AllUsersText":"Todos los usuarios",
        "Historico":"Historico",
        "SessionMenuText":"menu de sesion de ",
        "Aceptada":"Aceptada",
        "EnProgreso":"En progreso",
        "Lista":"Lista",
        "Incompleta":"Incompleta",
        "Anulada":"Anulada",
        "Borrada":"Borrada",
        "Listo":"Listo",
        "errorSetEstadoRexText":"Error actualizando el estado del rex:",
        "newPwd2Short":"La clave nueva debe poseer 6 o mas caracteres!",
        "mustBeEqualPwds":"La clave nueva y la clave a confirmar deben ser iguales!",
        "errorSetNewPwd":"Problemas con el cambio de clave: ",
        "setNewPwdOk":"Cambio de clave exitoso",
        "wantReStartDossier":"Deseas re-iniciar Dossier?",
        "editDC":"Editar DataClip",
        "EditStatus":"Cambio Estado",
        "Imprimir":"Imprimir",
        "DCSaved":"DC Corregido",
        "PrevDC":"DC Antiguo",
        "EditDC":"Editar Dataclip",
        "errorGeoLocation":"FYI: Servicio Geolocation fallo.",
        "errorBrowserNoSupportGeoloc":"FYI: tu browser no soporta geolocation.",
        "AgregarTarea":"Agregar Tarea",
        "OrdenarDCs":"Ordenar Dataclips",
        "RotIzq":"rota a la izq",
        "RotDer":"rota a la der",
        "AgregarDC":"Agregar DataClip",
        "AgregarImg":"Agregar Imagen",
        "OtrasOps":"Otras Operaciones",
        "errorRDSRadioCheck":"Error trayendo data en Radio/Check",
        "errorGetJsonSpin":"Error leyendo data en Spin",
        "Selecciona":"Selecciona ...",
        "errorGetAssetsJson":"Error leyendo data de Assets",
        "NotFound":"No se encontro",
        "errorRds":"Error leyendo data remota",
        "errorIdNotRespondigFP":"Verificar protocolo de Scaneo, Id no corresponde",
        "errorNoProfileSet":"No tiene perfil asignado",
        "PorLic":"por licenciamiento",
        "NotReg":"porque No esta registrado",
        "NoFPScanner":"porque No se localiza lector biometrico",
        "errorCaptura":"porque Error en proceso de captura",
        "errorGeneralFP":"porque Error general del proceso",
        "errorCapturaImagenTemplate":"porque Error en proceso de captura de imagen y template dactilar",
        "errorBDConnect":"porque Error de conexion con base de datos",
        "noConnectNServer":"porque No hay comunicacion con el servidor de comparaciones",
        "FPCanceled":"por Proceso cancelado",
        "errorNserver":"porque Error de actualizacion en NServer",
        "incorrectParameters":"porque Parametros de request incorrectos",
        "FPRegistrada":"porque Huella dactilar ya se encuentra registrada",
        "FPIdRegistrado":"porque Nro de Id ya esta registrado",
        "noRegistroDeFPEnNserver":"porque No se realizo el registro biometrico efectivamente en NServer",
        "unknownError":"desconocido",
        "quieresLogout":"Deseas cerrar tu sesion de trabajo?"
    },
    {
        "Titles en html":"",
        "IngresaId":"Ingresa tu identificacion",
        "IngresaPwd":"Ingresa tu Clave",
        "iconRotateLeft":"rota a la izq",
        "iconRotateRight":"rota a la der",
        "iconAddDC":"Agregar DataClip",
        "iconAddTask":"Agregar Tarea",
        "aicon":"menu de sesion",
        "BuscarEnDossiers":"Buscar en el contenido de los Dossiers",
        "iconSelectGrupo":"Para seleccionar el grupo",
        "iconSelEquipo":"Para indicar un solo miembro del grupo",
        "SelStatusTitle":"Para indicar el estado del Dossier",
        "iconRangoFecha":"Indicar el rango de fecha a buscar",
        "ButSubirEnMemoria":"Subir los Dossiers en memoria",
        "butDondeBusqueda":"Donde esta la Busqueda",
        "iconRefresh":"refrescar",
        "GraficarDossiers":"Graficar Dossiers",
        "iconExportaExcel":"Exporta a Excel(csv)",
        "iconPrint":"Imprimir",
        "iconChartSelectGroup":"Para seleccionar el grupo",
        "iconTipoDossier":"Selecciona la carpeta",
        "ChartIconSelDC":"Selecciona un DataClip",
        "iconSelCampoDC":"Selecciona un campo del DC",
        "iconChartSelectSello":"Selecciona un sello",
        "iconChartEstadoDossier":"Para indicar el estado del Dossier",
        "iconChartMiembroEquipo":"Para indicar un solo miembro del grupo",
        "iconChartRangoFecha":"Indicar el rango de fecha a buscar",
        "iconChartPeq":"mas pequeno",
        "iconChartRefresh":"refrescar",
        "expandicon":"mas grande",
        "iconChartRefresh2":"refrescar",
        "expandicon2":"mas grande",
        "iconChartPeq2":"mas pequeno",
        "iconChartRefresh3":"refrescar",
        "expandicon3":"mas grande",
        "iconChartPeq3":"mas pequeno",
        "IngresaClaveText":"Ingresa tu Clave actual",
        "IngresaClaveNuevaText":"Ingresa tu Clave nueva",
        "ConfirmaClaveNuevaText":"Confirma tu Clave nueva",
        "Editando":"Editando DC",
        "DCcamera":"Toma Foto",
        "DCgallery":"Incorpora Imagen",
        "PdfDC":"Incorpora PDF",
        "DCFingerPrintButt":"Identificacion biometrica",
        "DCsignature":"Incorpora Firma",
        "DeleteImagefromDC":"Desincorpora Imagen Anexa",
        "ImportSelected":"Importar info de DC seleccionado"       
    },
    {
        "alt Texts": "",
        "NextCameraIcon":"Otra Camara",
        "TakeFotoIcon": "Toma Foto"
    },
    {
        "innerHTML Text":"",
        "CameraTitle":"Camara",
        "Donde1":" Donde",
        "Donde3":"Donde",
        "Cuando1":" Cuando",
        "Cuando3":"Cuando",
        "Estadisticas1":" Estadisticas",
        "Estadisticas3":"Estadisticas",
        "Graficos3":"Grafico",
        "CerrarSesion":"cerrar sesion",
        "CambioPwd":"cambiar clave",
        "FirstSelGrupoOption":"Todos",
        "FirstSelEquipoOption":"Todos",
        "SelStatus1":"Activos",
        "SelStatus2":"Historicos",
        "SelStatus3":"Cerrados",
        "SelStatus0":"Borrados",
        "BuscarButton":"<span class='glyphicon glyphicon-search'></span> Buscar",
        "CantTareasPend":" Tareas",
        "CantRemindersPend":" Recordatorios",
        "CantDatesPend":" Citas",
        "CantEnMemoria":" En Memoria",
        "CantidadDossiers":"Cantidad",
        "ChartFirstSelGrupoOption":"Todos",
        "ChartFirstSelDossierOption":"Todos",
        "FirstChartDCOption":"Todos",
        "SelCamposMostrar":"Selecciona los campos a mostrar",
        "ChartFirstSelloOption":"Sin sello",
        "ChartStatusActivos":"Activos",
        "ChartStatusHistoricos":"Historicos",
        "ChartStatusActHist":"Activos e Historicos",
        "FirstChartOptionEquipo":"Todos",
        "TextoArchivoGaleria":"Archivo de Imagen",
        "TextSelFile":"Selecciona una imagen",
        "NoSelText":"Sin seleccionar",
        "PdfFileText":"Archivo PDF",
        "SelPdfText":"Selecciona un doc pdf",
        "NoPdfSelected":"Sin seleccionar",
        "CalendarText":"Calendario",
        "EstadisticasText":"Estadisticas",
        "iconArriba":"arriba",
        "EstadoTextOtrasOps":"Estado:",
        "ActivoStatusText":"Activo",
        "HistStatusText":"Historico",
        "BorradoStatusText":"Borrado",
        "SetRexStatusButt":"Cambiar Estado",
        "ChangePwdText":"Cambio de Clave:",
        "PwdActualText":"actual",
        "PwdNuevoText":"nueva",
        "PwdConfirmText":"confirma",
        "ButCambiaPwd":"Cambiar Clave",
        "Editor_DataClipName":"Nombre DataClip",
        "SignatureText":"Firma aqui",
        "SellosText":"Sellos",
        "SellosComentarioText":"Comentario:",
        "OrdenarDCText":"Ordenar los DC",
        "AddFileText":"Anexo de Imagen",
        "AddFileDescText":"Descripcion:",
        "AddFileSelImageText":"Selecciona una imagen",
        "AddFileNoSel":"Sin seleccionar",
    },
    {
        "Placeholders":"",
        "enTitulo":"Buscar en Dossier",
        "TextoChart":"Filtrar con este Texto",
        "iconChartSelectGroup":"Para seleccionar el grupo"
    }

];
function SetCurrentLanguageTexts(){
    var elem=null;
    
    for(var Tit in langtext[1]){//Titles
        try{
            elem = document.getElementById(Tit);
            elem.title = langtext[1][Tit];
        }catch(e){}
    }
    for(var alts in langtext[2]){//Titles
        try{
            elem = document.getElementById(alts);
            elem.alt = langtext[2][alts];
        }catch(e){}
    }
    for(var inners in langtext[3]){//Titles
        try{
            elem = document.getElementById(inners);
            elem.innerHTML = langtext[2][inners];
        }catch(e){}
    }
    for(var places in langtext[4]){//Titles
        try{
            elem = document.getElementById(places);
            elem.placeholder = langtext[2][places];
        }catch(e){}
    }

}




