# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - superdeker2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fb8dcec586bf4aa69196c2a66af4673a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_96f70e7eb455441c86302fa3650f63eb }}

    - run: |
        docker build . -t index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fb8dcec586bf4aa69196c2a66af4673a }}/ios app:${{ github.sha }}
        docker push index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fb8dcec586bf4aa69196c2a66af4673a }}/ios app:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'superdeker2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ae06dbcfadc647a9a5f34653f2cc49fe }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fb8dcec586bf4aa69196c2a66af4673a }}/ios app:${{ github.sha }}'